version 1.0.0

diff --git a/.github/workflows/android-ci-gradle.yml b/.github/workflows/android-ci-gradle.yml
--- a/.github/workflows/android-ci-gradle.yml
+++ b/.github/workflows/android-ci-gradle.yml
@@ -1,68 +1,87 @@
-name: Android Publish
-
+name: Android CI
 on:
   push:
-    branches:
-      - main
+    branches: ["main"]
+  pull_request:
+    branches: ["main"]
+env:
+  ANDROID_BUILD_TOOLS_VERSION: "34.0.0"
+  ANDROID_COMPILE_SDK: 34
+  ANDROID_TARGET_SDK: 34
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash -e {0}
 
     steps:
-      - name: Checkout Code
+      - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Set Up JDK
+      - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
-          distribution: 'adopt'
+          distribution: 'temurin'
           java-version: '17'
 
-      - name: Change wrapper permissions
+      - name: Grant execute permissions for gradlew
         run: chmod +x ./gradlew
 
-      - name: Set Build Tools Version
-        run: echo "buildToolsVersion=34.0.0" >> gradle.properties
-
-      - name: Update Gradle Wrapper
-        run: ./gradlew wrapper --gradle-version=8.2
-
-      - name: Run Tests
-        run: ./gradlew test
-
-      - name: Build Project
-        run: ./gradlew build
-
-      - name: Build Release AAB
-        run: ./gradlew bundleRelease
-
-      - name: Decode Signing Key and Store as keystore.jks
-        run: |
-          echo "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 -d > keystore.jks
-
-      - name: Sign AAB
-        run: |
-          java -jar bundletool.jar build-apks --bundle=app/build/outputs/bundle/release/app-release.aab --output=app/build/outputs/bundle/release/app-release-signed.apks --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTOREPASSWORD }} --ks-key-alias ${{ secrets.ALIAS }} --key-pass pass:${{ secrets.KEYPASSWORD }}
-
-      - name: Sign APK
-        run: |
-          apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTOREPASSWORD }} --ks-key-alias ${{ secrets.ALIAS }} --key-pass pass:${{ secrets.KEYPASSWORD }} --in app/build/outputs/apk/release/app-release-unsigned.apk --out app/build/outputs/apk/release/app-release-signed.apk
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v2
+      - name: Setup Android SDK
+        uses: android-actions/setup-android@v2
         with:
-          name: release-artifacts
-          path: |
-            app/build/outputs/bundle/release/*.aab
-            app/build/outputs/bundle/release/app-release-signed.apks
-            app/build/outputs/apk/release/app-release-signed.apk
+          sdk-version: "${{ env.ANDROID_BUILD_TOOLS_VERSION }}"
 
-      - name: List Files
+      - name: Print Gradle version
+        run: ./gradlew -v
+
+      - name: Build with Gradle
+        run: ./gradlew bundleRelease  # Build the release bundle
+
+      - name: Print Gradle Output Location
         run: |
-          ls -R app/build/outputs/bundle/release/
-          ls -R app/build/outputs/apk/release/
+          echo "Gradle output location: $(pwd)/app/build/outputs/bundle/release/"
 
-      - name: Display Artifact Token
-        run: echo ${{ github.token }}
+      - name: Check APK File Existence
+        run: |
+          if [ ! -f "$(pwd)/app/build/outputs/bundle/release/app-release.aab" ]; then
+            echo "Error: App Bundle file not found!"
+            exit 1
+          fi
+
+      - name: Install Android Build Tools
+        run: sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}"
+
+      - name: Sign the App Bundle
+        run: |
+          # Decode the Android signing key and save it as keystore.jks
+          echo "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 -d > keystore.jks
+          
+          # Sign the App Bundle
+          apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTOREPASSWORD }} --ks-key-alias ${{ secrets.ALIAS }} --key-pass pass:${{ secrets.KEYPASSWORD }} --in app/build/outputs/bundle/release/app-release.aab --out app/build/outputs/bundle/release/app-release-signed.aab
+          
+          # Verify the signed App Bundle
+          apksigner verify --verbose app/build/outputs/bundle/release/app-release-signed.aab
+
+
+      - name: Check Signed APK File Existence
+        run: |
+          if [ ! -f "$(pwd)/app-release-signed.apk" ]; then
+            echo "Error: Signed APK file not found!"
+            exit 1
+          fi
+
+      - name: Print Secret Variables for Debugging
+        run: |
+          echo "KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTOREPASSWORD }}"
+          echo "KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYPASSWORD }}"
+
+      - name: Upload App Bundle and Signed APK
+        uses: actions/upload-artifact@v4
+        with:
+          name: android-artifacts
+          path: |
+            app/build/outputs/bundle/release/app-release.aab
+            app-release-signed.apk
